### ISSUE TITLE
Github Repo Errors, KeyError

### ISSUE THREAD

**Issue by sfxworks** [emptycrown/llama-hub#136]
For some repositories (I can't find a consistent one between public/private org/user) I get key errors

For example, when pulling from kubernetes/website, I get 

```
<llama_index.readers.llamahub_modules.github_repo.base.GithubRepositoryReader object at 0x7f79f271be50>
current path: 
Traceback (most recent call last):
  File "/home/sam/git/mcsh/test2/repo.py", line 21, in <module>
    docs = loader.load_data(branch="main")
  File "/home/sam/.local/lib/python3.10/site-packages/llama_index/readers/llamahub_modules/github_repo/base.py", line 312, in load_data
    return self._load_data_from_branch(branch)
  File "/home/sam/.local/lib/python3.10/site-packages/llama_index/readers/llamahub_modules/github_repo/base.py", line 277, in _load_data_from_branch
    blobs_and_paths = self._loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/sam/.local/lib/python3.10/site-packages/llama_index/readers/llamahub_modules/github_repo/base.py", line 348, in _recurse_tree
    tree_data: GitTreeResponseModel = await self._github_client.get_tree(
  File "/home/sam/.local/lib/python3.10/site-packages/llama_index/readers/llamahub_modules/github_repo/github_client.py", line 365, in get_tree
    return GitTreeResponseModel.from_json(
  File "/home/sam/.local/lib/python3.10/site-packages/dataclasses_json/api.py", line 65, in from_json
    return cls.from_dict(kvs, infer_missing=infer_missing)
  File "/home/sam/.local/lib/python3.10/site-packages/dataclasses_json/api.py", line 72, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "/home/sam/.local/lib/python3.10/site-packages/dataclasses_json/core.py", line 201, in _decode_dataclass
    init_kwargs[field.name] = _decode_generic(field_type,
  File "/home/sam/.local/lib/python3.10/site-packages/dataclasses_json/core.py", line 263, in _decode_generic
    res = _get_type_cons(type_)(xs)
  File "/home/sam/.local/lib/python3.10/site-packages/dataclasses_json/core.py", line 317, in <genexpr>
    items = (_decode_dataclass(type_arg, x, infer_missing)
  File "/home/sam/.local/lib/python3.10/site-packages/dataclasses_json/core.py", line 159, in _decode_dataclass
    field_value = kvs[field.name]
KeyError: 'url'
```

For a private org, I get 
```
<llama_index.readers.llamahub_modules.github_repo.base.GithubRepositoryReader object at 0x7f1b7701fe50>
Traceback (most recent call last):
  File "/home/sam/git/mcsh/test2/repo.py", line 21, in <module>
    docs = loader.load_data(branch="main")
  File "/home/sam/.local/lib/python3.10/site-packages/llama_index/readers/llamahub_modules/github_repo/base.py", line 312, in load_data
    return self._load_data_from_branch(branch)
  File "/home/sam/.local/lib/python3.10/site-packages/llama_index/readers/llamahub_modules/github_repo/base.py", line 272, in _load_data_from_branch
    branch_data: GitBranchResponseModel = self._loop.run_until_complete(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/sam/.local/lib/python3.10/site-packages/llama_index/readers/llamahub_modules/github_repo/github_client.py", line 340, in get_branch
    return GitBranchResponseModel.from_json(
  File "/home/sam/.local/lib/python3.10/site-packages/dataclasses_json/api.py", line 65, in from_json
    return cls.from_dict(kvs, infer_missing=infer_missing)
  File "/home/sam/.local/lib/python3.10/site-packages/dataclasses_json/api.py", line 72, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "/home/sam/.local/lib/python3.10/site-packages/dataclasses_json/core.py", line 159, in _decode_dataclass
    field_value = kvs[field.name]
KeyError: 'commit'
```
And when I reference that private org's commit hash instead of the branch, I get
```
Traceback (most recent call last):
  File "/home/sam/git/mcsh/test2/repo.py", line 21, in <module>
    docs = loader.load_data(commit="cec867380358c611a78eaf58a0c282062b7d877f")
TypeError: GithubRepositoryReader.load_data() got an unexpected keyword argument 'commit'
```

Works on other repos though, including mine

**Comment by mrariden** [comment]
I also get a `KeyError: 'commit' ` for any repo I try. 

The issue over on the llama_index repo, [The GithubRepositoryReaderDemo can't run successfully #616](https://github.com/jerryjliu/llama_index/issues/616), seems similar. I can't run the demo either:
 
Code: 
```python {.scrollable}
import os
import nest_asyncio
from llama_index import download_loader
download_loader("GithubRepositoryReader")

from llama_index.readers.llamahub_modules.github_repo import GithubRepositoryReader, GithubClient
os.environ['GITHUB_TOKEN'] = 'my token'

nest_asyncio.apply()

github_client = GithubClient(os.getenv("GITHUB_TOKEN"))
loader = GithubRepositoryReader(
    github_client,
    owner =                  "jerryjliu",
    repo =                   "gpt_index",
    filter_directories =     (["gpt_index", "docs"], GithubRepositoryReader.FilterType.INCLUDE),
    filter_file_extensions = ([".py"], GithubRepositoryReader.FilterType.INCLUDE),
    verbose =                True,
    concurrent_requests =    10,
)

docs_branch = loader.load_data(branch="main")
```

I think the error is related to weird `nest_asyncio` stuff after some initial debugging. My taceback suggests that it's a bad return from `self._load_data_from_branch(branch)` in `GithubRepositoryReader.load_data`

**Comment by MattiPaivike** [comment]
I had this exact same issue and was able to resolve it by creating "personal access token (classic)" and selecting all scopes under "repo". Probably does not need all of those, but I am too lazy to start debugging what scopes exactly are really needed.

**Comment by sfxworks** [comment]
> I had this exact same issue and was able to resolve it by creating "personal access token (classic)" and selecting all scopes under "repo". Probably does not need all of those, but I am too lazy to start debugging what scopes exactly are really needed.

So I didn't mention but I also tried this. Still encountered the same issues.

![image](https://user-images.githubusercontent.com/5921035/228079244-e816e1fa-456d-4ef6-802b-3063837ff20a.png)

**Comment by mrariden** [comment]
I realized I'm dumb and didn't think to check other GH repos... 

jerryjliu renamed the repo to `llama_index` which is why `repo=gpt_index` couldn't find the commit. 

I guess the demo is broken tho.

**Comment by VladoPortos** [comment]
I still am getting 
```
 field_value = kvs[field.name]
KeyError: 'commit'
```

issue

**Comment by mrariden** [comment]
@VladoPortos double check that you're referencing the correct repo and owner. For the demo code you have to change `repo = gpt_index` to `repo = llama_index` because the repo was renamed.

**Comment by VladoPortos** [comment]
@mrariden yea, it was my mistake, I had empty space in front of the repo name... and the class does not strip empty spaces, it always fails with that error when either owner is wrong or the repo name... would be nice to get something more readable. Like user or repo, not found :D

**Comment by EmanuelCampos** [comment]
Example for github repo loader is already fixed

**Comment by nick-youngblut** [comment]
Wouldn't it be better to either just provide a warning instead of `KeyError: 'commit'`, or at least provide a more useful error message than simply `KeyError: 'commit'`? 

Many developers will likely get this vague error and have to find this issue in order to figure out what is going on.
