### ISSUE TITLE
WikipediaReader = download_loader("WikipediaReader")  error 

### ISSUE THREAD

**Issue by andrewholliday** [emptycrown/llama-hub#150]
**PptxReader = download_loader("PptxReader")**
C:\ProgramData\Anaconda3\lib\site-packages\llama_index\readers\llamahub_modules/file/pptx/requirements.txt
Traceback (most recent call last):

  File "<ipython-input-10-4582892469a6>", line 1, in <module>
    PptxReader = download_loader("PptxReader")

  File "C:\ProgramData\Anaconda3\lib\site-packages\llama_index\readers\download.py", line 192, in download_loader
    pkg_resources.require([str(r) for r in requirements])

  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 956, in require
    needed = self.resolve(parse_requirements(requirements))

  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 815, in resolve
    dist = self._resolve_dist(

  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 844, in _resolve_dist
    env = Environment(self.entries)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1044, in __init__
    self.scan(search_path)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1077, in scan
    self.add(dist)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 1096, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)

  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2631, in hashcmp
    self.parsed_version,

  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2685, in parsed_version
    raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None

**InvalidVersion: Invalid version: 'c3986' (package: -)**

**Any ideas. It does appear the __pycache__ directory and a base.cpython-38 file are not created like other readers.**

**Comment by EmanuelCampos** [comment]
It should be fixed. update your llamahub version and feel free to open the issue again if needed.
