### ISSUE TITLE
github_repo loader HTTP Exception

### ISSUE THREAD

**Issue by olafgeibig** [emptycrown/llama-hub#186]
Hi,

I'm trying to index a Java repo that I've forked. I'm sure I set up the permissions of the token correctly. The loader starts recursing the directories and generates documents. The error seems to occur when the loader starts to actually download the blobs from github. The console output is full of successful 'generating document' logging like the first line below and then the error occurs.

```
generating document for src/main/java/de/mossgrabers/controller/akai/fire/view/Drum4View.java
got 9276 characters- adding to documents - src/main/java/de/mossgrabers/controller/akai/fire/view/Drum4View.java
HTTP Exception for https://api.github.com/repos/olafgeibig/DrivenByMoss/git/blobs/fd0796c93578fffd67d3305db4189c8015dd6acc - [Errno 8] nodename nor servname provided, or not known
Traceback (most recent call last):
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/anyio/_core/_sockets.py", line 186, in connect_tcp
    addr_obj = ip_address(remote_host)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: 'api.github.com' does not appear to be an IPv4 or IPv6 address
```

## Script and Environment
MacOs 13.2 Ventura, Python 3.9 installed via homebrew, installed openai and llama-index via pip3 command. I tried Python 3.11 but same problem.

```python
from llama_index import download_loader, GPTSimpleVectorIndex
download_loader("GithubRepositoryReader")

from llama_index.readers.llamahub_modules.github_repo import GithubClient, GithubRepositoryReader

    github_client = GithubClient(os.getenv("GITHUB_TOKEN"))
    loader = GithubRepositoryReader(
        github_client,
        owner =                  "olafgeibig",
        repo =                   "DrivenByMoss",
        filter_directories =     (["src"], GithubRepositoryReader.FilterType.INCLUDE),
        filter_file_extensions = ([".java"], GithubRepositoryReader.FilterType.INCLUDE),
        verbose =                True,
        concurrent_requests =    10,
    )

    docs = loader.load_data(branch="master")
```
Error happens in the last line. Line 30

The problem must have something to do with content under the src/main/java/de/mossgrabers/framework directory. If I omit it, then the content is indexed properly.

## Full Tracebacks

```
HTTP Exception for https://api.github.com/repos/olafgeibig/DrivenByMoss/git/blobs/fd0796c93578fffd67d3305db4189c8015dd6acc - [Errno 8] nodename nor servname provided, or not known
Traceback (most recent call last):
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/anyio/_core/_sockets.py", line 186, in connect_tcp
    addr_obj = ip_address(remote_host)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/ipaddress.py", line 53, in ip_address
    raise ValueError('%r does not appear to be an IPv4 or IPv6 address' %
ValueError: 'api.github.com' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpcore/backends/asyncio.py", line 111, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/anyio/_core/_sockets.py", line 189, in connect_tcp
    gai_res = await getaddrinfo(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpcore/_async/connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpcore/backends/auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpcore/backends/asyncio.py", line 111, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/GEO5BE4/work/private/mygpt/main.py", line 30, in <module>
    docs = loader.load_data(branch="master")
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/llama_index/readers/llamahub_modules/github_repo/base.py", line 312, in load_data
    return self._load_data_from_branch(branch)
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/llama_index/readers/llamahub_modules/github_repo/base.py", line 283, in _load_data_from_branch
    return self._loop.run_until_complete(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/llama_index/readers/llamahub_modules/github_repo/base.py", line 420, in _generate_documents
    async for blob_data, full_path in buffered_iterator:
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/llama_index/readers/llamahub_modules/github_repo/utils.py", line 82, in __anext__
    await self._fill_buffer()
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/llama_index/readers/llamahub_modules/github_repo/utils.py", line 156, in _fill_buffer
    results: List[GitBlobResponseModel] = await asyncio.gather(
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/llama_index/readers/llamahub_modules/github_repo/github_client.py", line 392, in get_blob
    await self.request(
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/llama_index/readers/llamahub_modules/github_repo/github_client.py", line 320, in request
    raise excp
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/llama_index/readers/llamahub_modules/github_repo/github_client.py", line 315, in request
    response = await _client.request(
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/GEO5BE4/Library/Python/3.9/lib/python/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 8] nodename nor servname provided, or not known
```

**Comment by EmanuelCampos** [comment]
It ran successfully here

I recommend you to update to the latest version if isn't fixed yet

Closing due to inactivity and since we had a lot of fixes and improvements on this loader, feel free to open again if needed
