### ISSUE TITLE
`RDFReader` refactoring

### ISSUE THREAD

**Issue by namedgraph** [emptycrown/llama-hub#313]
Hi,

I have been trying out the `RDFReader` and noticed a few shortcomings.

It fails with an exception on arbitrary RDF files where entities cannot be expected to have `rdfs:label` values. Moreover, `Literal` objects cannot have labels at all, but the `load_data` method does not account for that at all:
```
Traceback (most recent call last):
  File "/Users/Martynas.Jusevicius/WebRoot/llama-index-test/test.py", line 8, in <module>
    documents = loader.load_data(file=Path('./skos.rdf'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Martynas.Jusevicius/WebRoot/llama-index-test/rdf_reader.py", line 75, in load_data
    f"<{self.fetch_label_in_graphs(o, lang=lang)}>"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Martynas.Jusevicius/WebRoot/llama-index-test/rdf_reader.py", line 49, in fetch_label_in_graphs
    raise Exception(f"Label not found for: {uri}")
Exception: Label not found for: A concept scheme may be defined to include concepts from different sources.
```

Secondly, there are many more different properties other than `rdfs:label` that are used as labels in RDF, e.g. `dcterms:title`, `skos:prefLabel` etc. Hardcoding a single property severely limits the applicability of this code. I suggest to introduce a user-specified [SPARQL query](https://rdflib.readthedocs.io/en/stable/intro_to_sparql.html) as a constructor param, which would select the labels from the graph. `load_data` would then walk a tabular query result set instead of the full graph.
The default query would replicate the current behavior with `rdfs:label`.

I also have a few questions:
* what is the purpose of falling back to RDF and RDFS graphs (`self.g_global`) in label search?
* does the following example represent the correct document format?
```
<history note> <type> <Property>
<has top concept> <range> <Concept>
<has narrower match> <subPropertyOf> <is in mapping relation with>
<has broader> <type> <Property>
<has narrower> <subPropertyOf> <has narrower transitive>
```

If you're OK with the above, I can make a PR.

**Comment by Demirrr** [comment]
Fully agreed with the observation of @namedgraph.  We should be able to read an RDF data without enforcing the label information. Is there any update on this @namedgraph @EmanuelCampos ?
