### ISSUE TITLE
llama-hub - RDF Loader get error: rdflib.exceptions.ParserError: Invalid line: 'Student'@en .

### ISSUE THREAD

**Issue by chenkuncloud** [emptycrown/llama-hub#322]
Hi,

I am trying to use RDFReader to generate an index for `llama_index`, and the code is consistent with [llama-hub - RDF Loader](https://llama-hub-ui.vercel.app/l/file-rdf), as follows:
```
from pathlib import Path
from llama_index import download_loader

RDFReader = download_loader("RDFReader")

loader = RDFReader()
documents = loader.load_data(file=Path('./mytest-graph.nt'))
```

mytest-graph.nt:
```
<http://example.org/ontology/Student> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Class> .
<http://example.org/ontology/School> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#Class> .
<http://example.org/ontology/Student> <http://www.w3.org/2000/01/rdf-schema#label> 'Student'@en .
<http://example.org/ontology/School> <http://www.w3.org/2000/01/rdf-schema#label> 'School'@en .
<http://example.org/ontology/studyingAt> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#ObjectProperty> .
<http://example.org/ontology/studyingAt> <http://www.w3.org/2000/01/rdf-schema#label> 'studying at'@en .
<http://example.org/resource/student1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.org/ontology/Student> .
<http://example.org/resource/student1> <http://www.w3.org/2000/01/rdf-schema#label> 'student1'@en .
<http://example.org/resource/school1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://example.org/ontology/School> .
<http://example.org/resource/school1> <http://www.w3.org/2000/01/rdf-schema#label> 'school1'@en .
<http://example.org/resource/student1> <http://example.org/ontology/studyingAt> <http://example.org/resource/school1> .
```

But I get error:
```
Traceback (most recent call last):
  File "D:\developer\Python\Python\lib\site-packages\rdflib\plugins\parsers\ntriples.py", line 168, in parse
    self.parseline(bnode_context=bnode_context)
  File "D:\developer\Python\Python\lib\site-packages\rdflib\plugins\parsers\ntriples.py", line 219, in parseline
    object_ = self.object(bnode_context)
  File "D:\developer\Python\Python\lib\site-packages\rdflib\plugins\parsers\ntriples.py", line 254, in object
    raise ParseError("Unrecognised object type")
rdflib.exceptions.ParserError: Unrecognised object type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\temp\build.py", line 7, in <module>
    documents = loader.load_data(file=Path('./mytest-graph.nt'))
  File "D:\developer\Python\Python\lib\site-packages\llama_index\readers\llamahub_modules/file/rdf/base.py", line 59, in load_data
    self.g_local.parse(file)
  File "D:\developer\Python\Python\lib\site-packages\rdflib\graph.py", line 1330, in parse
    parser.parse(source, self, **args)
  File "D:\developer\Python\Python\lib\site-packages\rdflib\plugins\parsers\ntriples.py", line 343, in parse
    parser.parse(f, **kwargs)
  File "D:\developer\Python\Python\lib\site-packages\rdflib\plugins\parsers\ntriples.py", line 170, in parse
    raise ParseError("Invalid line: {}".format(self.line))
rdflib.exceptions.ParserError: Invalid line: 'Student'@en .
```

My version:
* windows 10
* Python 3.10.0
* rdflib 6.2.0
* pathlib 1.0.1

Did I do something wrong?

Best regards

**Comment by namedgraph** [comment]
@chenkuncloud your data is not valid N-Triples. Replace single quotes with double quotes on literals.

**Comment by chenkuncloud** [comment]
> @chenkuncloud your data is not valid N-Triples. Replace single quotes with double quotes on literals.

Hi, @namedgraph 

Thanks. I am very glad to receive your reply!
After adjusting the issue of single quotes marks, I can use `llama_index` to generate an index from rdf.

But I have another question, how does `LangChain` use [llama-hub - RDF Loader](https://llama-hub-ui.vercel.app/l/file-rdf) to generate an index?

My python code get an error. Did I do something wrong?
```python
from pathlib import Path
from llama_index import download_loader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings.openai import OpenAIEmbeddings
from langchain.vectorstores import FAISS

RDFReader = download_loader("RDFReader")
loader = RDFReader()
documents = loader.load_data(file=Path('data/mytest-graph.nt'))

text_splitter = RecursiveCharacterTextSplitter(chunk_size=100, chunk_overlap=0)
texts = text_splitter.split_documents(documents)

db = FAISS.from_documents(texts, OpenAIEmbeddings())
db.save_local("myindex")
```
```text
Traceback (most recent call last):
  File "......\PyCharm\PyCharm Community Edition 2022.3.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "......\PyCharm\PyCharm Community Edition 2022.3.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "......\rdf\build.py", line 16, in <module>
    texts = text_splitter.split_documents(documents)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "......\Python-3.11.4\Lib\site-packages\langchain\text_splitter.py", line 112, in split_documents
    texts.append(doc.page_content)
                 ^^^^^^^^^^^^^^^^
AttributeError: 'Document' object has no attribute 'page_content'
python-BaseException

Process finished with exit code 1
```

Best regards

**Comment by EmanuelCampos** [comment]
Closing now due to inactivity
