### ISSUE TITLE
llama-hub - RDF Loader get error: raise Exception(f"Label not found for: {uri}")

### ISSUE THREAD

**Issue by chenkuncloud** [emptycrown/llama-hub#356]
Hi,

I am trying to use [llama_index RDFReader](https://llama-hub-ui.vercel.app/l/file-rdf) to generate an index , but get error.

My python code:
```python
from pathlib import Path
from llama_index import download_loader

RDFReader = download_loader("RDFReader")

loader = RDFReader()
documents = loader.load_data(file=Path('./mytest-graph.nt'))
```

mytest-graph.nt:
```text
<http://www.w3.org/2002/07/owl#DatatypeProperty> <http://www.w3.org/2000/01/rdf-schema#label> "DatatypeProperty"@en .
<http://example.org/ontology/description> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2002/07/owl#DatatypeProperty> .
<http://example.org/ontology/description> <http://www.w3.org/2000/01/rdf-schema#label> "description"@en .
<http://example.org/resource/school1> <http://www.w3.org/2000/01/rdf-schema#label> "school1"@en .
<http://example.org/resource/student1> <http://example.org/ontology/description> "Student1 is a boy, 15 years old, with the goal of becoming a programmer"@en .
```

Error:
```text
Traceback (most recent call last):
  File "D:\developer\PyCharm\PyCharm Community Edition 2022.3.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\developer\PyCharm\PyCharm Community Edition 2022.3.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "......\llamaindex\RDFReader\student2\build.py", line 10, in <module>
    documents = loader.load_data(file=Path('data/mytest-graph.nt'))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\developer\Python\Python-3.11.4\Lib\site-packages\llama_index\readers\llamahub_modules/file/rdf/base.py", line 73, in load_data
    f"<{self.fetch_label_in_graphs(o, lang=lang)}>"
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\developer\Python\Python-3.11.4\Lib\site-packages\llama_index\readers\llamahub_modules/file/rdf/base.py", line 49, in fetch_label_in_graphs
    raise Exception(f"Label not found for: {uri}")
Exception: Label not found for: Student1 is a boy, 15 years old, with the goal of becoming a programmer
python-BaseException
```

Version:
* windows 10
* Python 3.10.0

After my experiment, if I only use `rdf:type` and `rdfs:label` (i.e. remove the last rdf triple), it succeeded.
but when I add the custom attribute `ontology:description`, it failed.
What is the reason for this?

Did I do something wrong?

Best regards

**Comment by chenkuncloud** [comment]
After reading [RDF Loader's base.py](https://github.com/emptycrown/llama-hub/blob/main/llama_hub/file/rdf/base.py), it turns out that RDF Loader is actually converting RDF into the form of the following text:
```text
<subject's label> <predicate's label> <object's label>
<subject's label> <predicate's label> <object's label>
......
```

Moreover, RDF Loader requires that the object must be uri, and uri must have a label. 
If there is a customization requirement, RDF can be converted into text form by oneself.
