### ISSUE TITLE
Github _repo: number of requests limit

### ISSUE THREAD

**Issue by simoneVU** [emptycrown/llama-hub#529]
I keep getting this error when I try collecting a lot of Github repositories together @ahmetkca :

```
tree object: GitTreeResponseModel.GitTreeObject(path='_layouts', mode='040000', type='tree', sha='bee1987427564cdeebc6df740df0600dca0e9a72', url='https://api.github.com/repos/dabeaz-course/practical-python/git/trees/bee1987427564cdeebc6df740df0600dca0e9a72', size=None)
recursing into _layouts
        current path: _layouts
HTTP Exception for https://api.github.com/repos/dabeaz-course/practical-python/git/trees/bee1987427564cdeebc6df740df0600dca0e9a72 - 
Traceback (most recent call last):
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/anyio/_core/_sockets.py", line 190, in connect_tcp
    addr_obj = ip_address(remote_host)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: 'api.github.com' does not appear to be an IPv4 or IPv6 address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/anyio/_core/_tasks.py", line 115, in fail_after
    yield cancel_scope
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/anyio/_core/_sockets.py", line 193, in connect_tcp
    gai_res = await getaddrinfo(
              ^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/asyncio/tasks.py", line 339, in __wakeup
    future.result()
  File "/home/simonec/.conda/envs/py311/lib/python3.11/asyncio/futures.py", line 198, in result
    raise exc
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7ff86e713210

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 113, in connect_tcp
    with anyio.fail_after(timeout):
  File "/home/simonec/.conda/envs/py311/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/anyio/_core/_tasks.py", line 118, in fail_after
    raise TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 262, in handle_async_request
    raise exc
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpcore/_async/connection.py", line 92, in handle_async_request
    raise exc
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpcore/_async/connection.py", line 69, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpcore/_async/connection.py", line 117, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 112, in connect_tcp
    with map_exceptions(exc_map):
  File "/home/simonec/.conda/envs/py311/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/simonec/Desktop/Github/READMEGPT/src/get_repos_files.py", line 83, in <module>
    df_final = download_github_repo_files(df, owners_1, full_names_1, def_branches_1)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/Desktop/Github/READMEGPT/src/get_repos_files.py", line 29, in download_github_repo_files
    docs = loader.load_data(branch=def_branch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/llama_hub/github_repo/base.py", line 301, in load_data
    return self._load_data_from_branch(branch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/llama_hub/github_repo/base.py", line 268, in _load_data_from_branch
    blobs_and_paths = self._loop.run_until_complete(self._recurse_tree(tree_sha))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
           ^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/asyncio/futures.py", line 203, in result
    raise self._exception.with_traceback(self._exception_tb)
  File "/home/simonec/.conda/envs/py311/lib/python3.11/asyncio/tasks.py", line 267, in __step
    result = coro.send(None)
             ^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/llama_hub/github_repo/base.py", line 365, in _recurse_tree
    await self._recurse_tree(
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/llama_hub/github_repo/base.py", line 335, in _recurse_tree
    tree_data: GitTreeResponseModel = await self._github_client.get_tree(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/llama_hub/github_repo/github_client.py", line 368, in get_tree
    await self.request(
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/llama_hub/github_repo/github_client.py", line 321, in request
    raise excp
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/llama_hub/github_repo/github_client.py", line 316, in request
    response = await _client.request(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/home/simonec/.conda/envs/py311/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/simonec/.conda/envs/py311/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout
```

It happens randomly with different repository, and I think it is because of the GitHub limit for a github app, is there a way to fix it? It really happens rather randomly, e.g. if I do not do any other request with the GitHub API before it usually collects more repositories, otherwise, it returns the error earlier.

This is the code I am running:

```
def download_github_repo_files(df, owners, full_names, def_branches):
    for owner, repo_name, def_branch in zip(owners, full_names, def_branches):
        loader = GithubRepositoryReader(
            github_client,
            owner =                  owner,
            repo =                   repo_name,
            filter_file_extensions = ([".py"], GithubRepositoryReader.FilterType.INCLUDE),
            verbose =                True,
            use_parser =             False,
            concurrent_requests =    5,
        )
        print("Owner: ", owner, "Repo: ", repo_name, "Branch: ", def_branch)
        docs = loader.load_data(branch=def_branch)

        with open('code.txt', 'w') as f:
            f.write('Python files from which the readme is based on. Note that \n\n\nSOP = Start of Path, EOP = End of Path, SOF = Start of File, EOF = End of File\n\n\n')
        #For all files in docs, get the file paths and their text
        file_contents, file_paths = [], []
        for doc in docs:
            file_paths.append(doc.metadata['file_path'])
            file_contents.append(doc.text)

            #Write doc.metadata['file_path'] and doc.text to a.txt file
            with open('code.txt', 'a') as f:
                #End of Path: EOP
                #Start of Path: SOP
                f.write("SOP\n" + doc.metadata['file_path'] + ' EOP\n')
                #End of Content: EOF
                #Start of Content: SOF
                f.write("#SOF\n" + doc.text + '\n#EOF\n\n\n')

        #Read .txt file as a string
        with open('code.txt', 'r') as f:
            file_paths_and_contents = f.read()

        #Add new row to datafram df_python
        df.loc[(df['repo_name'] == repo_name) & (df['user_name'] == owner), 'code'] = file_paths_and_contents

    return df
```
I assumed the error happens because of the number of requests, but I might be wrong too. Any help would be really appreciated!

**Comment by EmanuelCampos** [comment]
You can check the Github rate limit for personal accounts here:

https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-personal-accounts

5000 requests per hour per account,

There are other rules and best practices on how to deal with rate-limiting, like waiting 1 second per request, etc...

https://docs.github.com/en/rest/guides/best-practices-for-using-the-rest-api?apiVersion=2022-11-28#dealing-with-rate-limits
https://docs.github.com/en/rest/guides/best-practices-for-using-the-rest-api?apiVersion=2022-11-28#dealing-with-secondary-rate-limits

Maybe check on the headers `x-ratelimit-reset` before making a request again

Feel free to open a PR and contribute with us when figured out
