### ISSUE TITLE
[Bug]: Add embedding_llm parameter to OpenAIAgent.from_tools for Azure OpenAI deployment

### ISSUE THREAD

**Issue by dino1729** [emptycrown/llama-hub#554]
### Bug Description

I am trying to use the google search tool but I get this error when I try to use it with LoadAndSearchToolSpec wrapper.

The agent is setup to handle a custom llm but not embedding_llm

Need to add an additional embedding_llm parameter support to handle declarations like:
agent = OpenAIAgent.from_tools(
    tools, 
    llm=llm,
    embedding_llm=embedding_llm,
    verbose=True
)

### Version

0.8.33

### Steps to Reproduce

Run the agent with azure openai service

### Relevant Logs/Tracbacks

```shell
"=== Calling Function ===
Calling function: google_search with args: {
  "query": "latest news about India"
}
Traceback (most recent call last):
  File "/<hidden_path>/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/<hidden_path>/llama_index/embeddings/openai.py", line 169, in get_embeddings
    data = openai.Embedding.create(input=list_of_text, model=engine, **kwargs).data
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<hidden_path>/openai/api_resources/embedding.py", line 33, in create
    response = super().create(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<hidden_path>/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<hidden_path>/openai/api_resources/abstract/engine_api_resource.py", line 83, in __prepare_create_request
    raise error.InvalidRequestError(
openai.error.InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a <class 'openai.api_resources.embedding.Embedding'>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/<hidden_path>/test_scripts/llamaagent_google.py", line 97, in <module>
    print(agent.chat("whats the latest news summary about India"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<hidden_path>/llama_index/callbacks/utils.py", line 38, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<hidden_path>/llama_index/agent/openai_agent.py", line 344, in chat
    chat_response = self._chat(
                    ^^^^^^^^^^^
  File "/<hidden_path>/llama_index/agent/openai_agent.py", line 295, in _chat
    self._call_function(tools, self.latest_function_call)
  File "/<hidden_path>/llama_index/agent/openai_agent.py", line 220, in _call_function
    function_message, tool_output = call_function(
                                    ^^^^^^^^^^^^^^
  File "/<hidden_path>/llama_index/agent/openai_agent.py", line 55, in call_function
    output = tool(**argument_dict)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/<hidden_path>/llama_index/tools/types.py", line 125, in __call__
    return self.call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<hidden_path>/llama_index/tools/function_tool.py", line 82, in call
    tool_output = self._fn(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<hidden_path>/llama_index/tools/tool_spec/load_and_search/base.py", line 131, in load
    self._index = self._index_cls.from_documents(docs, **self._index_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<hidden_path>/llama_index/indices/base.py", line 102, in from_documents
    return cls(
           ^^^^
  File "/<hidden_path>/llama_index/indices/vector_store/base.py", line 47, in __init__
    super().__init__(
  File "/<hidden_path>/llama_index/indices/base.py", line 71, in __init__
    index_struct = self.build_index_from_nodes(nodes)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<hidden_path>/llama_index/indices/vector_store/base.py", line 236, in build_index_from_nodes
    return self._build_index_from_nodes(nodes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<hidden_path>/llama_index/indices/vector_store/base.py", line 224, in _build_index_from_nodes
    self._add_nodes_to_index(
  File "/<hidden_path>/llama_index/indices/vector_store/base.py", line 184, in _add_nodes_to_index
    nodes = self._get_node_with_embedding(nodes, show_progress)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<hidden_path>/llama_index/indices/vector_store/base.py", line 98, in _get_node_with_embedding
    id_to_embed_map = embed_nodes(
                      ^^^^^^^^^^^^
  File "/<hidden_path>/llama_index/indices/utils.py", line 136, in embed_nodes
    new_embeddings = embed_model.get_text_embedding_batch(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<hidden_path>/llama_index/embeddings/base.py", line 231, in get_text_embedding_batch
    embeddings = self._get_text_embeddings(cur_batch)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<hidden_path>/llama_index/embeddings/openai.py", line 362, in _get_text_embeddings
    return get_embeddings(
           ^^^^^^^^^^^^^^^
  File "/<hidden_path>/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/<hidden_path>/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/<hidden_path>/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x11c5eda10 state=finished raised InvalidRequestError>]"
```

**Comment by dino1729** [comment]
There is a workaround for this issue. By setting the service_context and set_global_service_context, the error goes away

**Comment by EmanuelCampos** [comment]
It's not an issue, if you need to set a service_context for the indexes you can do as the example below

The agent doesn't receive embeddings, since it just needs to call the LLM

```py
LoadAndSearchToolSpec.from_defaults(tool, index_kwargs={"service_context": service_context})
```
